name: VocabSpark
options:
  bundleIdPrefix: com.yourname
  deploymentTarget:
    iOS: "17.0"
  defaultConfig: Debug
settings:
  base:
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    DEVELOPMENT_LANGUAGE: de
    TARGETED_DEVICE_FAMILY: "1,2" # iPhone + iPad
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown"

targets:
  VocabSpark:
    type: application
    platform: iOS
    sources:
      - path: Sources/FrenchVocab
    configFiles:
      Debug: Config.xcconfig
      Release: Config.xcconfig
    info:
      path: Sources/FrenchVocab/Info.plist
      properties:
        CFBundleDisplayName: "VocabSpark"
        CFBundleShortVersionString: "1.0.1"
        CFBundleVersion: "2"
        UILaunchScreen:
          UIColorName: ""
        OPENAI_API_KEY: "$(OPENAI_API_KEY)"
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.michikoenig.vocabspark
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        MARKETING_VERSION: "1.0.1"
        CURRENT_PROJECT_VERSION: "2"
    scheme:
      testTargets: []
